Fix ZZZ & Add custom header functionality
canaria3406/hoyolab-auto-sign pull request #55
Opened 2024-10-11 08:41 UTC by WiLuX-Source

Fixes #52

2024-10-11 08:42 UTC, WiLuX-Source commented
Tested discord english version.
Other versions needs testing but should be fine.

2024-10-11 09:15 UTC, Chillrend commented on src/main-telegram_zh-tw.gs
> -  for (const url of urls) {
You removed this part at your PR, pretty sure it's not intentional.

2024-10-11 09:17 UTC, Chillrend requested changes

2024-10-11 09:17 UTC, Chillrend commented on src/main-telegram_zh-tw.gs
> -  }
You removed this from your PR, pretty sure its not intentional..

2024-10-11 09:26 UTC, WiLuX-Source commented on src/main-telegram_zh-tw.gs
> -  }
Ah that needs fixing thank you.

2024-10-11 10:29 UTC, WiLuX-Source commented
Ok should be fine for now. thank you @Chillrend

2024-10-12 01:49 UTC, Chillrend approved these changes
Okay looks good!

2024-10-12 22:32 UTC, StarPlayingGames approved these changes

2024-10-14 07:34 UTC, rounak-codes approved these changes

2024-10-31 03:00 UTC, itsPG approved these changes

2024-11-17 12:24 UTC, heymeowcat approved these changes

2024-11-17 12:32 UTC, heymeowcat approved these changes

2024-11-20 15:06 UTC, WiLuX-Source commented
It seems this project is dead and I need to go seperate go direction. If you liked how I coded this PR you might be interested in my version thanks everyone who approved.

2024-11-21 08:09 UTC, canaria3406 reviewed
thanks

2024-11-21 08:09 UTC, merged